spring.application.name=Back

spring.datasource.url=jdbc:firebirdsql://localhost:3050/${user.dir}/../DADOS.FDB?charSet=utf-8
spring.datasource.username=SYSDBA
spring.datasource.password=1811
spring.datasource.driver-class-name=org.firebirdsql.jdbc.FBDriver

spring.jpa.database-platform=org.hibernate.dialect.FirebirdDialect
spring.jpa.hibernate.ddl-auto=none